Terms of Use
CoinAIfy — Coin & Banknote Identifier Effective Date: April 15, 2026 Last Updated: April 15, 2026



1. Acceptance of Terms
By downloading, installing, or using the CoinAIfy mobile application ("App") on any Apple iOS device, you ("User") agree to be bound by these Terms of Use ("Terms"). If you do not agree to these Terms, you must not use the App. These Terms constitute a legally binding agreement between you and CoinAIfy ("we," "us," or "our").

Your continued use of the App following any modification to these Terms constitutes your acceptance of the revised Terms. We encourage you to review these Terms periodically.



2. Description of the App
CoinAIfy is an AI-powered mobile application designed to help numismatists, collectors, and enthusiasts identify, grade, and estimate the market value of coins and banknotes by analyzing photographs captured through the device camera. The App provides informational results including denomination, condition assessment, historical context, rarity, and estimated market value ranges. All valuations are AI-generated estimates and are provided for informational and educational purposes only.



3. Eligibility
You must be at least 13 years of age to use the App. If you are under 18, you must have the consent of a parent or legal guardian who agrees to be bound by these Terms on your behalf. By using the App, you represent and warrant that you meet these eligibility requirements.



4. Account Registration
Certain features of the App may require you to create an account. You agree to provide accurate, current, and complete information during registration and to update such information to keep it accurate. You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You must notify us immediately of any unauthorized use of your account.



5. Subscription Plans and In-App Purchases
5.1 Free Trial
CoinAIfy offers a 2-day free trial that provides full access to all premium features, including unlimited scans, professional-grade AI valuations, and the Collection Manager. This is a limited time introductory offer and may be modified or discontinued at any time. The free trial automatically converts to a paid subscription at the end of the trial period unless cancelled before the trial expires.

5.2 Subscription Tiers
After the free trial, access to premium features requires an active subscription. The following plans are available:

Plan	Price	Billing Cycle
Monthly	$4.99	Billed monthly
Annual	$19.99	Billed annually (save ~67%)
Lifetime Access	$79.99	One-time payment
Prices are in US dollars and are subject to change. Applicable taxes may apply depending on your jurisdiction.

5.3 Billing and Renewal
Subscriptions are billed through your Apple ID account via the App Store. Your subscription will automatically renew at the end of each billing period unless auto-renewal is turned off at least 24 hours before the end of the current period. Your account will be charged for renewal within 24 hours prior to the end of the current period. You can manage or cancel your subscription at any time through your Apple ID account settings.

5.4 Refunds
All purchases are processed by Apple and are subject to Apple's refund policy. CoinAIfy does not directly issue refunds for in-app purchases. To request a refund, please visit reportaproblem.apple.com.



6. AI-Generated Valuations — Disclaimer
The coin and banknote identifications, grades, and market value estimates provided by the App are generated by artificial intelligence and are estimates only. They do not constitute professional numismatic appraisals, financial advice, or guarantees of value. Actual market values may differ significantly based on factors including but not limited to physical condition, provenance, current market demand, and the opinion of a certified numismatist.

You should not rely solely on the App's output when making buying, selling, or investment decisions. We strongly recommend consulting a certified coin dealer or professional appraiser (such as a member of the Professional Numismatists Guild or the American Numismatic Association) before transacting based on any value estimate provided by the App.



7. Acceptable Use
You agree to use the App only for lawful purposes and in a manner consistent with these Terms. You must not:

•	Use the App to facilitate fraud, misrepresentation, or the sale of counterfeit currency or coins.
•	Attempt to reverse-engineer, decompile, or disassemble any portion of the App.
•	Use automated tools, bots, or scripts to access or interact with the App.
•	Circumvent, disable, or interfere with security-related features of the App.
•	Upload or transmit images that contain illegal content or that violate the rights of any third party.
•	Use the App in any manner that could damage, disable, or impair the App or its servers.



8. Intellectual Property
All content within the App, including but not limited to the App's name, logo, design, text, graphics, AI models, and software, is the exclusive property of CoinAIfy or its licensors and is protected by applicable intellectual property laws. You are granted a limited, non-exclusive, non-transferable, revocable license to use the App solely for your personal, non-commercial purposes in accordance with these Terms.

You retain ownership of any images you capture or upload through the App. By submitting images to the App, you grant CoinAIfy a limited, worldwide, royalty-free license to process those images solely for the purpose of providing the App's identification and valuation services. We do not store your images on our servers beyond the duration necessary to generate a scan result, unless you explicitly save items to your Collection.



9. Privacy
Your use of the App is also governed by our Privacy Policy, which is incorporated into these Terms by reference. The Privacy Policy describes how we collect, use, and share information about you when you use the App. By using the App, you consent to the data practices described in the Privacy Policy.



10. Third-Party Services
The App may integrate with or link to third-party services, including the Apple App Store, mapping services for the Nearby Dealers feature, and payment processing services. Your use of such third-party services is governed by their respective terms and privacy policies. CoinAIfy is not responsible for the content, accuracy, or practices of any third-party service.



11. Limitation of Liability
To the fullest extent permitted by applicable law, CoinAIfy and its officers, directors, employees, and agents shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, loss of data, or loss of goodwill, arising out of or in connection with your use of or inability to use the App, even if we have been advised of the possibility of such damages.

Our total liability to you for any claims arising under these Terms shall not exceed the amount you paid to CoinAIfy in the twelve (12) months preceding the claim.



12. Disclaimer of Warranties
The App is provided on an "as is" and "as available" basis without warranties of any kind, either express or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, and non-infringement. We do not warrant that the App will be uninterrupted, error-free, or free of viruses or other harmful components. We do not warrant the accuracy, completeness, or usefulness of any information provided by the App.



13. Indemnification
You agree to indemnify, defend, and hold harmless CoinAIfy and its officers, directors, employees, and agents from and against any claims, liabilities, damages, losses, and expenses, including reasonable legal fees, arising out of or in any way connected with your access to or use of the App, your violation of these Terms, or your violation of any rights of another person or entity.



14. Termination
We reserve the right to suspend or terminate your access to the App at any time, with or without notice, for any reason, including if we reasonably believe you have violated these Terms. Upon termination, your right to use the App will immediately cease. Sections 6, 8, 11, 12, 13, and 16 of these Terms shall survive termination.



15. Changes to the App
We reserve the right to modify, suspend, or discontinue the App (or any part thereof) at any time, with or without notice. We shall not be liable to you or any third party for any modification, suspension, or discontinuation of the App.



16. Governing Law and Dispute Resolution
These Terms shall be governed by and construed in accordance with the laws of the State of California, United States, without regard to its conflict of law provisions. Any dispute arising out of or relating to these Terms or the App shall first be submitted to informal negotiation. If the dispute cannot be resolved informally within 30 days, it shall be resolved by binding arbitration in accordance with the rules of the American Arbitration Association, conducted in English in San Francisco, California.

Notwithstanding the foregoing, either party may seek injunctive or other equitable relief in a court of competent jurisdiction to prevent the actual or threatened infringement of intellectual property rights.



17. Apple-Specific Terms
The following terms apply to your use of the App obtained through the Apple App Store:

•	These Terms are concluded between you and CoinAIfy only, and not with Apple Inc. ("Apple"). Apple is not responsible for the App or its content.
•	Apple has no obligation whatsoever to furnish any maintenance and support services with respect to the App.
•	In the event of any failure of the App to conform to any applicable warranty, you may notify Apple, and Apple will refund the purchase price for the App to you (if applicable). To the maximum extent permitted by applicable law, Apple will have no other warranty obligation whatsoever with respect to the App.
•	Apple is not responsible for addressing any claims by you or any third party relating to the App or your possession and use of the App.
•	Apple and Apple's subsidiaries are third-party beneficiaries of these Terms and, upon your acceptance of these Terms, Apple will have the right (and will be deemed to have accepted the right) to enforce these Terms against you as a third-party beneficiary thereof.



18. Contact Us
If you have any questions, concerns, or feedback regarding these Terms, please contact us at:

CoinAIfy Support Email: coinaify@gmail.com



These Terms of Use were last updated on April 15, 2026. By continuing to use CoinAIfy, you acknowledge that you have read, understood, and agree to be bound by these Terms.
